### PR TITLE
fix: Alphabetically order the rules

### PR DESCRIPTION
**Pull request by bmds**
Order the rules alphabetically to make finding them easier when we add more

### CODE REVIEW

**Comment by tawashley** [comment]
@bmds What scope does this have? Documentation - `README.md`? `.eslintrc.json` or is this for code (where you know my stance)

**Comment by furzeface** [comment]
👍 :octocat:

**Comment by bmds** [comment]
@tawashley This is purely for within the ESlint.json file within the rules section. This could potentially get quite large. It's just preemptively ordering them alphabetically so that when we add more it's easier to discover existing ones to avoid potential duplicates

**Comment by bmds** [comment]
@tawashley Might not have been clear before. this isn't me adding a rule but ordering the rule declarations we've got

**Comment by tawashley** [comment]
@bmds Do you want reviewers to merge it in, or yourself?

**Pull request merged**
